spring :
  datasource:
    url: ${RDS_HOST}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

jwt:
  secret: ${JWT_KEY}

server:
  error:
    include-stacktrace: never

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.assignment.cartservice.dto
  configuration:
    map-underscore-to-camel-case: true

